name: cffdrs
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - dask
  - geopandas
  - h5netcdf
  - numpy>=1.17.3,<1.25.0
  - python=3.9.15
  - rasterio
  - shapely
  - tqdm
  - xarray
  - xclim=0.40.0
prefix: /home/jdpaul3/miniconda3/envs/cffdrs
